#!/usr/bin/env python3
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from hbin.server import main  # noqa: E402

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
